server:
  port: 8080
  servlet:
    contextPath: /api

spring:
  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:3306/db_webservice?serverTimezone=UTC
    username: root
    password: P@ssw0rd